config/routes.rb
Rails.application.routes.draw do
  resources :users
	get 'welcome/index'
	
	resources :bugs
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
	enum issue_type: [:Issue, :Enhancement, :Feature]
	enum priority: [:Low, :Medium, :High]
	enum status: [:Open, :Closed, :Monitor]

	validates :title, presence: true
	validates :description, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	validates :fname, :lname, :email, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
	validates :thumbnail, allow_blank: true, format: {with: %r{\.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG, or PNG image.'}

	has_many :bugs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, :set_issue_types, :set_priorities, :set_statuses, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
    respond_to do |format|
      format.html {render :index}
      format.json {render :index, status: :ok}
      format.xml {render xml: @bugs.as_json}
    end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    user = User.find(bug_params[:user_id])
    @bug.build_user(:id => user.id)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    def set_issue_types
      @issue_types = Bug.issue_types
    end

    def set_priorities
      @priorities = Bug.priorities
    end

    def set_statuses
      @statuses = Bug.statuses
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :issue_type, :priority, :status, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@bugs = Bug.last(3)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    thumb_upload = params[:user][:thumbnail]
    params[:user][:thumbnail] = thumb_upload.original_filename

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    thumb_upload = params[:user][:thumbnail]
    params[:user][:thumbnail] = thumb_upload.original_filename
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:lname, :fname, :email, :thumbnail)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bugs/_form.html.erb
<%= form_with(model: bug, local: true) do |form| %>
  <% if bug.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.select :user_id, options_for_select(User.all.collect {|u| ["#{u.fname} #{u.lname}", u.id]}, selected: (@bug.user ? @bug.user.id : User.first.id)), {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :issue_type %>
    <%= form.select :issue_type, Bug.issue_types.keys, selected: @bug.issue_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :priority %>
    <%= form.select :priority, Bug.priorities.keys, selected: @bug.priority, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, Bug.statuses.keys, selected: @bug.status, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', bugs_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<div id="main" class="container">
	<h1>Editing Bug</h1>

	<%= render 'form', bug: @bug %>
</div>

app/views/bugs/index.html.erb
<div id="main" class="container">

  <% if !notice.blank? %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>

  <h1>Bugs</h1>

  <table class="table table-hover table-mobile">
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Description</th>
        <th>Issue type</th>
        <th>Priority</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @bugs.each do |bug| %>
        <tr>
          <td>
            <%= (bug.user.try(:fname)) %> <%= (bug.user.try(:lname) || "N/A") %>
          </td>
          <td><%= bug.title %></td>
          <td><%= bug.description %></td>
          <td><%= bug.issue_type %></td>
          <td><%= bug.priority %></td>
          <td><%= bug.status %></td>
          <td class="nowrap">
            <%= link_to bug, class: "btn btn-default btn-sm" do %>
              Show
            <% end %>
         
            <%= link_to edit_bug_path(bug), class: "btn btn-default btn-sm" do %>
              Edit
            <% end %>
          
            <%= link_to bug, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" do %>
              Delete
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Bug', new_bug_path, :class => "btn btn-primary" %>
</div>

app/views/bugs/new.html.erb
<div id="main" class="container">
	<h1>New Bug</h1>

	<%= render 'form', bug: @bug %>
</div>

app/views/bugs/show.html.erb
<div id="main" class="container">
  <% if !notice.blank? %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>

  <p>
    <strong>User:</strong>
    <%= (@bug.user.try(:fname)) %> <%= (@bug.user.try(:lname) || "N/A") %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @bug.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @bug.description %>
  </p>

  <p>
    <strong>Issue type:</strong>
    <%= @bug.issue_type %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= @bug.priority %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @bug.status %>
  </p>

  <%= link_to 'Edit', edit_bug_path(@bug), class: "btn btn-primary" %>
  <%= link_to 'Back', bugs_path, class: "btn btn-danger" %>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="content-underlay">
			<h1>BugOverflow</h1>
			<p>
				A simple bug tracker for a simple life.
			</p>
			<p>
				<a class="btn btn-primary btn-lg" href="#" role="button">
					Learn more &raquo;
				</a>
			</p>
		</div>
	</div>
</div>

<div class="container-fluid">
	<h2>Recent Bugs</h2>
	<!-- Example row of columns -->
	<div class="row">
		<% @bugs.each do |bug| %>
			<div class="col-md-4">
				<h3><%= bug.title%></h3>
				<p>
					<%= bug.description.truncate_words(30)%>
				</p>
				<p>
					<%= link_to 'Read more >', bug, class: "btn btn-default"%>
				</p>
			</div>
		<% end %>
	</div>
	<hr>
	<footer>
		<p>
			&copy; 2018 Justin Wickenheiser
		</p>
	</footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="/">BugOverflow</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link navbar-dark" href="/">
					Home <span class="sr-only">(current)</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link navbar-dark" href="/users">Users</a>
			</li>
			<li class="nav-item">
				<a class="nav-link navbar-dark" href="/bugs">Bugs</a>
			</li>
			<li class="nav-item">
				<a class="nav-link navbar-dark" href="/ajax.html">Ajax Test</a>
			</li>
		</ul>
		<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugoverflow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong><%= form.label :lname %></strong>
    <%= form.text_field :lname, class: "form-control" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :fname %></strong>
    <%= form.text_field :fname, class: "form-control" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :email %></strong>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <strong><%= form.label :thumbnail %></strong>
    <%= form.file_field :thumbnail, class: "form-control-file" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', users_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="main" class="container">
	<h1>Editing User</h1>

	<%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<div id="main" class="container">

  <% if !notice.blank? %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>

  <h1>Users</h1>

  <table class="table table-hover table-mobile">
    <thead>
      <tr>
        <th>Lname</th>
        <th>Fname</th>
        <th>Email</th>
        <th>Thumbnail</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.lname %></td>
          <td><%= user.fname %></td>
          <td><%= user.email %></td>
          <td><%= user.thumbnail %></td>
          <td class="nowrap">
            <%= link_to user, class: "btn btn-default btn-sm" do %>
              Show
            <% end %>
          
            <%= link_to edit_user_path(user), class: "btn btn-default btn-sm" do %>
              Edit
            <% end %>
          
            <%= link_to user, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" do %>
              Delete
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path, :class => "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div id="main" class="container">
	<h1>New User</h1>

	<%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div id="main" class="container">
	<% if !notice.blank? %>
		<p id="notice" class="alert alert-success"><%= notice %></p>
	<% end %>

	<p>
		<strong>Lname:</strong>
		<%= @user.lname %>
	</p>

	<p>
		<strong>Fname:</strong>
		<%= @user.fname %>
	</p>

	<p>
		<strong>Email:</strong>
		<%= @user.email %>
	</p>

	<p>
		<strong>Thumbnail:</strong>
		<%= @user.thumbnail %>
	</p>

	<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %>
	<%= link_to 'Back', users_path, class: "btn btn-danger" %>
</div>

app/views/welcome/index.html.erb
<h1>Bug Overflow Project</h1>
<%= link_to 'Bug Overflow', controller: 'bugs' %>
<br />
<%= link_to 'Users', controller: 'users' %>